Name,Author,Link
https://design-justice.pubpub.org/,Sasha Costanza-Chock,
https://weaponsofmathdestructionbook.com/,Cathy O'Neil,
https://www.ruhabenjamin.com/race-after-technology,Ruha Benjamin,
https://datafeminism.io/,Catherine D’Ignazio and Lauren F. Klein,
https://nyupress.org/9781479837243/algorithms-of-oppression/,Safiya Noble,
,,
,,
,,
.,,